### ISSUE TITLE
switch causing error

### ISSUE THREAD

**Issue by sander2** [szabta89/IncA#6]
This code causes an error `type y8 is not a subtype of (node<>, node<FunctionArg>)`, located on the first alternative of `getUniqueInputLifetimes1`:

```
join type LifetimeDeclarator = Lifetime | PointerType
                                                     
private def getUniqueInputLifetimes1(f : Function) : (LifetimeDeclarator, FunctionArg) = { 
  arg := f.args 
  ty := arg.ty 
  q := typeGetUsedPointerTypes(ty) 
  switch { 
    assert undef q.lifetime 
    return (q, arg) 
  } alt { 
    lifetime := q.lifetime 
    decl := resolveLifetime(lifetime, lifetime) 
    return (decl, arg) 
  } 
}
```
Even though the manually desugared version works just fine:
```
private def getUniqueInputLifetimes2(f : Function) : (LifetimeDeclarator, FunctionArg) = { 
  arg := f.args 
  ty := arg.ty 
  q := typeGetUsedPointerTypes(ty) 
  assert undef q.lifetime 
  return (q, arg) 
} alt { 
  arg := f.args 
  ty := arg.ty 
  q := typeGetUsedPointerTypes(ty) 
  lifetime := q.lifetime 
  decl := resolveLifetime(lifetime, lifetime) 
  return (decl, arg) 
}
```

(code pushed to my `switch-error` branch)

**Comment by szabta89** [comment]
What do you think about the following? Given a switch statement, its type is going to be a join type where the component types are the types of the alternatives. This kinda contradicts the semantics of the switch because it lists several alternatives, so it would be more natural to use a meet type as its type, but then it is not clear how I could check the conformance to the expected return type of the function. Alternatively, it would be ok to compute the least common supertype of the individual alternative’s types and use that as the type of the switch, but in the presence of join types, it is not so easy to enumerate all supertypes of a node<…> type which would be required for a least common supertype computation.

**Comment by sander2** [comment]
Making the type of a `switch` to be the meet of its components does not make sense to me. Ultimately, you need to check whether the type of the switch is a subtype of the declared return type of the enclosing pattern function. By using the meet of the switch, one of the alternative of the switch might actually be a super type of the declared return type of the function.

I don't really get why type checking the switch is more difficult than type checking the pattern function. Is that because for a function you only need to check for a subtyping relation with the declared return type, and don't need to calculate a join of the types of the alternatives? If so, couldn't you do the same for a switch? I.e. just checking whether either (1) all alternatives of the switch return a subtype of the declared return type of the function, or (2) none of the alternatives of the switch return anything all?

**Comment by szabta89** [comment]
What you are suggesting here would require special treatment for the switch, meaning that we would need to check for the specific case when there is a switch as the last statement in a function. That is not the way to go, we want to have a type system that works out-of-the-box irrespective for the order of your constructs. 

Type checking the pattern function is "easier" because the structure is known by default: The function contains several alternatives. The switch being the last statement in one alternative is not necessarily the case.
